baseURL = "https://kidult-stage.com/"
languageCode = 'ko-kr'
title = 'kidult-stage : Never Stop Playing'
theme = 'congo'

enableRobotsTXT = true
summaryLength = 70

[pagination]
  pagerSize = 10

[params]
  colorScheme = "auto"
  defaultAppearance = "dark"
  autoSwitchAppearance = true

[params.homepage]
  layout = "page"
  homepageImage = ""
  showRecent = true
  showRecentItems = 5
  cardView = false
  cardViewScreenWidth = false

[params.article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "basic"
  layoutBackgroundBlur = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showSummary = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showReadingTime = true
  showComments = false

[params.list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = false
  groupByYear = false
  cardView = false

[params.sitemap]
  changefreq = "weekly"
  priority = 0.5

[params.taxonomy]
  showTermCount = true

[params.fathomAnalytics]
  site = ""

[menu]
  [[menu.main]]
    name = "블로그"
    pageRef = "posts"
    weight = 10
    
  [[menu.main]]
    name = "카테고리"
    pageRef = "categories"
    weight = 20
    
  [[menu.main]]
    name = "태그"
    pageRef = "tags"
    weight = 30

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
